config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  resources :recipes do
    resources :comments
  end

  get '/about'=> 'about#index', as: :about

  resources :sessions, only: [:new, :create]

  resources :users

  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  delete '/logout' => 'sessions#destroy', as: :logout


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  acts_as_taggable
  acts_as_taggable_on :recipe
  belongs_to :user

  scope :of_followed_users, -> (following_users) {where user_id: following_users}

  has_many :comments, dependent: :destroy

  # def self.search(search)
  #
  #   where("title ILike ?", "%#{search}%")
  # end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :recipes, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  validates :user_name, presence: true, length: {minimum: 4, maximum: 16}

  has_many :comments, dependent: :destroy

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :current_user_is_following, :follow, :unfollow, :search

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end

  def follow(current_user_id, user_id)
    @f = Follow.new
    @f.follower = current_user_id
    @f.following = user_id
    @f.save
  end

  def unfollow( user_id)
    @f = Follow.find_by(following_id: user_id).destroy
  end

  def search()
    if params[:search]
      @recipes = Recipe.tagged_with(params[:search]).order("created_at DESC")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_recipe
  before_action :find_comment, only: [:destroy, :edit, :update]
  def create

    @comment = @recipe.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to recipe_path(@recipe)
    else
      redirect_to users_path
    end
  end

  def edit

  end

  def update
    if @comment.update(comment_params)
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end

  end



  def destroy
    @comment.destroy
    redirect_to recipe_path(@recipe)
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def find_comment
    @comment = @recipe.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :owned_recipe, only: [:edit, :update, :destroy]
  def index
    # Recipes of followed users
    # @recipes = Recipe.of_followed_users(current_user.following).order('created_at DESC')
    @recipes = Recipe.all.order('created_at DESC')
    if params[:search]
      @recipes = Recipe.tagged_with(params[:search]).order("created_at DESC")
    else
      @recipe = Recipe.all.order('created_at DESC')
    end
  end

  def show

    @recipe = Recipe.find(params[:id])
    @comments = Comment.where(recipe_id: @recipe).order('created_at DESC')

    if params[:search]
      @search = params[:search]

      redirect_to root_path(@search)
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:success] = "New Recipe Created"
      redirect_to user_path(@recipe.user)
    else
      redirect_to new_recipe_path
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])

  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:success] = "Recipe has been updated"
      redirect_to user_path(@recipe.user)
    else
      redirect_to edit_recipe_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      redirect_to user_path(current_user)
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :ingredients, :instructions, :difficulty_level, :tag_list, :time)
  end

  def owned_recipe
    @recipe = Recipe.find(params[:id])
    unless current_user == @recipe.user
      redirect_to users_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController



  def follow_user
    @user = User.find(params[:id])

    if follow(current_user, @user)
      respond_to do |format|
        format.html {redirect_to user_path(@user)}
        format.js
      end
    end
  end

  def unfollow_user

    @user = User.find(params[:id])

    if unfollow(@user.id)
      respond_to do |format|
        format.html {redirect_to user_path(@user)}
        format.js
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "Incorrect Email or Passowrd"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]= "Account has been created"
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:success]= "Account has been updated"

      redirect_to user_path
    else
      redirect_to edit_user_path
    end
  end

  def following
    @user = User.find(params[:id])
    @users = User.all
  end
  def follower
    @user = User.find(params[:id])
    @users = User.all
  end

  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:name, :user_name, :email, :bio, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3>Comments:</h3>
    <% if @comments.count == 0 %>
    
    <p>Be the first to add a Comment!</p>
    <%else %>
    <% @comments.each do |comment| %>

    <div class="comments">
      <h4><%= link_to comment.user.name, user_path(comment.user.id) %>:  </h4>
      <p><%= comment.content %></p>
      <%= time_ago_in_words(comment.created_at) %> ago
    </div>

      <% if current_user == comment.user %>
      <%= link_to 'Delete comment', [comment.recipe, comment], method: "DELETE" %> |
      <%= link_to 'Edit comment', edit_recipe_comment_path(comment.recipe, comment) %>
      <%end %>

    <%end %>
    <%end %>
    <br>
    <h3>Add a Comment:</h3>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@recipe, @recipe.comments.build]) do |f| %>
  <p>
      <div class="form-group">
      <%= f.text_area :content,  class: 'form-control' %>
    </div>
  </p>
  <div class="form-group">
    <%= f.submit 'Add Comment', class: 'btn btn-success' %>
  </div>
<%end %>

app/views/comments/edit.html.erb
<%= form_for ([@recipe, @comment]) do |f| %>

    <p>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </p>
      <%= f.submit %>

<%end %>

app/views/forms/_recipe.html.erb
<%= form_for @recipe, :html => {class: 'new_user form-horizontal'} do |f| %>
  <div class="row"><legend class="col-md-4 col-md-offset-4">Add a Recipe:</legend></div>

  <fieldset>
      <div class="form-group">
        <%= f.label :title, 'Name:', class:'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ingredients, 'Ingredients:', class:'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_area :ingredients, class: 'form-control' %>
        </div>

      </div>
      <div class="form-group">
        <%= f.label :instructions, 'Directions:', class:'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_area :instructions, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :difficulty_level, 'Difficulty Level:', class:'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :difficulty_level, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :time, 'Time:', class:'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :time, class: 'form-control' %>
        </div>
      </div>
      <!-- Tags -->
      <div class="form-group">
        <%= f.label 'Tags:', class:'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :tag_list, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
          <%= f.submit 'Submit', class: 'btn btn-success' %>
        </div>
      </div>
  </fieldset>
  <%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Secret Ingredient</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render 'partials/navbar' %>
 <div class="container">

   <%if flash[:alert] %>
   <div class="alert alert-danger">
      <%= flash[:alert] %>
   </div>
   <%elsif flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
   <%end %>
   <%= yield %>

 </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand"  href="/">
        <img src="/logo-small.png" class="logo" >
      </a>

    </div>

    

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>


        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Profile', user_path(current_user)%></li>
              <li><%= link_to 'Profiles', users_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: 'DELETE' %></li>
            </ul>
          </li>
        <%else %>
        <li>  <%= link_to 'Login', new_session_path %></li>
        <%end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<%= render 'forms/recipe' %>

app/views/recipes/index.html.erb
<% if logged_in? %>
<div class="row">
<div class="col-md-4 col-offset-md-6" style="float: right;">
<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
  <%= form_tag(recipes_path, :method => 'get', id:"search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by Tags" %>
  <%= submit_tag "Search", :name =>nil %>
  <%end %>
  </div>
</form>
</div>
</div>
<legend class="col-md-12">Discover Recipes</legend>
    <% @recipes.each_slice(3) do |row| %>
        <div class="row">
        <% row.each do |l| %>
        <div class="col-md-12 box">
        <h4><%=link_to l.title, recipe_path(l.id)  %></h4>
          <p> <%= l.instructions %> </p>
        <h5> <%=l.user.name%>  </h5>
        <div class="tags"><%= l.tag_list %></div>
        </div>
    <%end %>
    </div>
    <% end %>
<%else %>
      <div class="about-bg">
      <div class="jumbotron">
          <h1>The Secret Ingredient </h1>
            <p>
              For those of you who are new, welcome! Think of this website as an online cookbook where you can post your favorite recipes and discover new recipes by following friends!
            </p>
          <%=link_to "Sign In", new_session_path,class: 'btn btn-success btn-lg'  %>
          <%=link_to "Create Account", new_user_path,class: 'btn btn-primary btn-lg'  %>
      </div>
      </div>
<%end %>

app/views/recipes/new.html.erb
<%= render 'forms/recipe' %>

app/views/recipes/show.html.erb
<h1> <%= @recipe.title%> </h1>
  <%= link_to 'Return to Profile', user_path(@recipe.user),class: 'btn btn-primary' %>
    <% if @recipe.user == current_user %>
      <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'btn btn-success'  %>
      <%= link_to 'Delete', recipe_path(@recipe), method: 'DELETE',class: 'btn btn-success' %>
    <%end %>

<div class="row">
  <div class="col-md-6">
    <h2>Ingredients</h2>
    <p>
      <% @i = @recipe.ingredients %>
      <% @i.each_line do |line| %>
    <li> <%= line %> </li>
      <%end %>
    </p>
  </div>
  <div class="col-md-6">
    <h2>Instructions</h2>
    <p>
      <%= @recipe.instructions %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <h3>Tags</h3>
      <p>
        <%= @recipe.tag_list %>
      </p>
  </div>
  <div class="col-md-4">
    <h2>Difficulty Level </h2>
    <p>
      <%= @recipe.difficulty_level %>
    </p>
  </div>
  <div class="col-md-4">
    <h2>Expected Time</h2>
    <p><%= @recipe.time %></p>
  </div>
</div>



<%= render 'comments/comment' %>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/relationships/follow_user.html.erb
<h1>Relationships#follow_user</h1>
<p>Find me in app/views/relationships/follow_user.html.erb</p>

app/views/relationships/unfollow_user.html.erb
<h1>Relationships#unfollow_user</h1>
<p>Find me in app/views/relationships/unfollow_user.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user, :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Edit Account:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :name, 'Name:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :name, 'User Name:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :user_name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :email, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :bio, 'Bio:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_area :bio, class: 'form-control' %>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
              <%= f.submit 'Update Account', class: 'btn btn-success' %>
  	        </div>
  	    </div>
    </fieldset>
<% end %>

app/views/users/follow_users.js.erb
$('#follow-button').attr('class', 'btn unfollow-button').text('Following').attr('href', '<%= @user.id%>/unfollow_user').attr('id', 'unfollow-button');
$('#unfollow-button').text('Follow').attr('class', 'btn follow-button').attr('href', "<%=@user.id%>/follow_user").attr('id', 'follow-button');

app/views/users/index.html.erb
<h2>Profiles:</h2>
<ul>
<% @users.each do |u| %>
  <li><strong><%= link_to u.name, user_path(u.id) %></strong>:
<% if u.recipes.count < 2 %>
  <%= u.recipes.count %> Recipe</li>
<% elsif u.recipes.count == 0 || u.recipes.count > 1%>
  <%= u.recipes.count %> Recipes</li>
<%end %>
<%end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user, :html => {class: 'new_user form-horizontal'} do |f| %>
    <div class="row"><legend class="col-md-4 col-md-offset-4">Create Account:</legend></div>
    <fieldset>
        <div class="form-group">
            <%= f.label :name, 'Name:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :name, 'User Name:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :user_name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.text_field :email, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :password, 'Password:', class: 'col-md-4 control-label' %>
            <div class="col-md-5">
                <%= f.password_field :password, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
              <%= f.submit 'Create Account', class: 'btn btn-success' %>
  		        <%= link_to "Already have an account?", new_session_path, class: 'btn btn-primary' %>
  	        </div>
  	    </div>
    </fieldset>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user %>
    <h3>My Profile</h3>
    <%= link_to 'Edit User', edit_user_path, class: 'btn btn-primary' %>
    <%= link_to 'Add Recipe', new_recipe_path, class: 'btn btn-success'  %>
<%else %>
    <h3><%= @user.user_name %></h3>

    <%if current_user_is_following(current_user.id, @user.id) %>
      <%= link_to 'Following', unfollow_user_path, method: :post, id:'unfollow-button',class:"btn btn-primary"%>
    <%else %>
      <%= link_to 'Follow', follow_user_path, method: :post, id:'follow-button',class:"btn btn-primary"%>
    <%end %>
<%end %>

<button type="button" class="btn btn-success" data-toggle="modal" data-target="#followers">Followers</button>

<div id="followers" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= @user.name %>'s followers: </h4>
      </div>

      <div class="modal-body">
        <ul>
          <% if @user.followers.count == 0 %>
            <%= @user.name %> does not have any followers
          <%else %>
            <%@user.followers.each do |n| %>
              <li><strong><%= link_to n.name, user_path(n.id) %></strong>:
                <% if n.recipes.count < 2 %>
                  <%= n.recipes.count %> Recipe</li>
                <% elsif n.recipes.count == 0 || n.recipes.count > 1%>
                    <%= n.recipes.count %> Recipes</li>

                  <%end %>
            <%end %>
          </ul>
          <%end %>
      </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>

    </div>

  </div>

</div>

<button type="button" class="btn btn-success" data-toggle="modal" data-target="#following">Following</button>

<div id="following" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= @user.name %> is following: </h4>
      </div>

      <div class="modal-body">
        <ul>
        <% if @user.following.count == 0 %>
          <%= @user.name %> is not following anyone.
        <%else %>
        <%@user.following.each do |n| %>
        <li><strong><%= link_to n.name, user_path(n.id) %></strong>:
          <% if n.recipes.count < 2 %>
            <%= n.recipes.count %> Recipe</li>
            <% elsif n.recipes.count == 0 || n.recipes.count > 1%>
              <%= n.recipes.count %> Recipes</li>
            <%end %>
        <%end %>
        </ul>
        <%end %>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>

</div>

<%if current_user_is_following(current_user.id, @user.id) || @user == current_user %>
  <h3>My Recipes:</h3>
  <ul>
    <% @user.recipes.each do |p| %>
      <li><%= link_to p.title, recipe_path(p) %></li>
    <%end %>
  </ul>
  <%else %>
    <h3>Follow <%= @user.user_name %> to see recipes!</h3>
<%end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>